### PR TITLE
db Pass URL info to vote endpoint

### PR DESCRIPTION
**Pull request by darraghjburke**
- Passes the URL of the search result into the vote request (this is useful so that the backend can generate a database entry if none currently exist)
- Removes the query parameter, which shouldn't be needed anymore

### CODE REVIEW

**Comment by darraghjburke** [comment]
May not want to merge this branch into master until we have changed the back end to remove the query parameter requirement

**Comment by pconrad** [comment]
So should this PR and #88 be merged together?

**Comment by pconrad** [comment]
It looks like you folks might be "done!" ... is this PR still useful to be merged?  What value does it add?

**Comment by darraghjburke** [comment]
> 
> 
> It looks like you folks might be "done!" ... is this PR still useful to be merged? What value does it add?

It was intended to lay the groundwork for #86. The idea was that, rather than storing every search result ever returned by the Google API in the database, we would only store search results once someone actually voted on them. We don't really need to know anything about search results with 0 votes.

The issue with this is that we would need to generate new SearchResultEntity's in the "/updateVote" endpoint rather than in the "/searchUpDownResults" endpoint. But in order to create a new SearchResultEntity, we need to know the URL of the result. So we'd have to pass in the URL as one of the parameters. That's what this PR accomplishes. We would still need to move the logic for creating new SearchResultEntity's from "/searchUpDownResults" to "/updateVote" later on.

Even if we don't bother implementing #86 this quarter, I'd still like to get this PR in, because it adds the URL encoding that @btk5h mentioned on Slack.

**Comment by pconrad** [comment]
@darraghjburke  can you look at the merge conflicts?

I wonder if rebasing on master would address some of them.

**Comment by darraghjburke** [comment]
@phtcon Resolved!

**Pull request merged**
