### PR TITLE
Jl restyle search page

### LINKED ISSUE #62: Restyle search page
Restyle the search page to look more like a real search engine.

### PR DESCRIPTION
**Pull request by jenny353**
Fixes #62 
Restyles Search page:

- retyles the search bar
- restyles the index page

### CODE REVIEW

**Comment by pconrad** [comment]
@jenny353 @jpcommissaris @btk5h @lucastnguyen    Can you fix the merge conflicts?

When you do, we can merge this! and give you points :-)

**Comment by jpcommissaris** [comment]
I can do it tonight

**Comment by jpcommissaris** [comment]
> @jenny353 @jpcommissaris @btk5h @lucastnguyen Can you fix the merge conflicts?
> 
> When you do, we can merge this! and give you points :-)

**Comment by jpcommissaris** [comment]
@pconrad finished with the merge conflicts

**Pull request merged**
